### ISSUE TITLE
Potential Leaked memory

### ISSUE THREAD

**Issue by sleepylee** [nhphong/nimble-surveys#11] opened 2019-04-10 16:19 UTC
From the Android Studio Profiler, while scrolling through the VP, the amount of allocated memory is suspiciously increased and held. Would you mind rechecking this?

**Comment by sleepylee** [comment] 2019-04-10 16:30
Actually...it's quite clear from your implementation I'm afraid.

**Comment by nhphong** [comment] 2019-04-11 04:31
The cause is: [here](https://github.com/nhphong/nimble-surveys/blob/5d4d688a93cabca071bfe3b2cc51bd73b116c694/app/src/main/java/com/nhphong/nimblesurveys/views/adapter/MainPagerAdapter.kt#L11)

It is because we've implemented an infinite View Pager by using `FragmentPagerAdapter`, instead of `FragmentStatePagerAdapter`.

Every time we navigate to the new page, `FragmentPagerAdapter` creates that page and caches it. It's only useful in case we have small number of pages.

`FragmentStatePagerAdapter` on the other hand, destroys the page when it is off-screen, and re-creates it when it's on-screen again. Source can be found [here](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter)

**Comment by nhphong** [comment] 2019-04-11 04:34
Actually, it's a balance between performance and memory. I've noticed this issue since the implementation but in the end, I chose performance. 😄

**Comment by nhphong** [comment] 2019-04-11 04:38
I have changed in in this commit: https://github.com/nhphong/nimble-surveys/pull/12/commits/fc356211f9a6fd77f35ab6e03dbccd72d1cc93d4

**Comment by sleepylee** [comment] 2019-04-11 06:04
please separate the issue per single responsibility PR 🙏 it helps us review the changes easier as well...also, for this process you won't need to wait for us to approve before merging, just go ahead after ur review and we will follow up 😉

**Comment by nhphong** [comment] 2019-04-11 06:31
Got it 👌 
I will create separate PR from the next issue.

**Comment by nhphong** [comment] 2019-04-12 04:32
@sleepylee can we close this issue?

**Comment by sleepylee** [comment] 2019-04-12 04:46
yes please go ahead 🙌

**Closed** 2019-04-12 04:49 UTC
